export const FORMULARIO_OBRA = 'FORMULARIO_OBRA'
export const OBTENER_OBRAS = 'OBTENER_OBRAS'
export const AGREGAR_OBRA = 'AGREGAR_OBRA';
export const VALIDAR_FORMULARIO = 'VALIDAR_FORMULARIO';
export const OBRA_ACTUAL = 'OBRA_ACTUAL';
export const ELIMINAR_OBRA = 'ELIMINAR_OBRA';
export const OBRA_ERROR = 'OBRA_ERROR';

export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';

export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION';